/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
//CLOCK CONFIGURATION
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile unsigned int *)(RCC_BASE+0x18)
//GPIO CONFIGURATION
//PORTA REGS
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *(volatile unsigned int *)(GPIOA_BASE+0x00)
#define GPIOA_CRH *(volatile unsigned int *)(GPIOA_BASE+0x04)
#define GPIOA_IDR *(volatile unsigned int *)(GPIOA_BASE+0x08)
#define GPIOA_ODR *(volatile unsigned int *)(GPIOA_BASE+0x0C)
//PORTB REGS
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRL *(volatile unsigned int *)(GPIOB_BASE+0x00)
#define GPIOB_CRH *(volatile unsigned int *)(GPIOB_BASE+0x04)
#define GPIOB_IDR *(volatile unsigned int *)(GPIOB_BASE+0x08)
#define GPIOB_ODR *(volatile unsigned int *)(GPIOB_BASE+0x0C)


#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *(volatile unsigned int *)(AFIO_BASE+0x08)
//EXTI CONFIGURATION
#define EXTI_BASE 0x40010400
#define EXTI_IMR *(volatile unsigned int *)(EXTI_BASE+0x00)
#define EXTI_RTSR *(volatile unsigned int *)(EXTI_BASE+0x08)
#define EXTI_PR *(volatile unsigned int *)(EXTI_BASE+0x14)
#define NVIC_EXTIE1 	*(volatile unsigned int*)(0xE000E100)
void gpio_init()
{
	GPIOA_CRL=0x0;
	GPIOA_CRH=0x0;
	GPIOA_ODR=0x0;
	GPIOB_CRL=0x0;
	GPIOB_CRH=0x0;
	GPIOB_ODR=0x0;
	//CONFIGURE PORTB PIN1 AS FLOATING INPUT
	//CNF1
	GPIOB_CRL |=(0b01<<6);
	//MODE1
	GPIOB_CRL &=~(0b11<<4);
	//CONFIGURE PORTA PIN5 AS OUTPUT PUSH-PULL
	//CNF1
	GPIOA_CRL &=~(0b11<<22);
	//MODE1
	GPIOA_CRL |=(0b01<<20);

}
void clock_init()
{
	//enable clock init for alternative I/O for apb2
	RCC_APB2ENR|=(1<<0);
	//port A clock enable
	RCC_APB2ENR|=(1<<1);
	//port B clock enable
	RCC_APB2ENR|=(1<<2);
}
void EXTI_INIT()
{
	//Interrupt request from Line 1 is not masked
	EXTI_IMR |=(1<<1);
	//Rising trigger enabled (for Event and Interrupt) for line1 as input
	EXTI_RTSR |=(1<<1);
	//select the pin 1 portB as a source input for EXTI line 1
	AFIO_EXTICR1|=(0001<<4);
	//enable irq for nvic
	NVIC_EXTIE1 |=(1<<7);
}


int main(void)
{
	gpio_init();
	clock_init();
	EXTI_INIT();
	while(1)
	{

	}
	return 0;

}
void EXTI1_IRQHandler(void)
{
	//IRQ IS HAPPENED>>EXTI1_|_RISING EDGE
	//PINA5
	GPIOA_ODR ^=(1<<5);
	//Pending register: cleared by writing a ‘1’ into the bit.
	//selected trigger request occurred
	EXTI_PR |=(1<<1);
}
